apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod
<<<<<<< HEAD
=======
  labels:
    app: nginx
>>>>>>> acdb203 (session 2 assignment)

spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80